services:
  mongo:
    image: mongo:7.0
    container_name: myapp_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - myapp_network   # הוסף!

  server:
    build: ./server
    container_name: myapp_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - myapp_network   # הוסף!

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - myapp_network   # הוסף!

  caddy:
    image: caddy:latest
    container_name: myapp_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client/build:/srv/app/client/build
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
    networks:
      - myapp_network   # כבר מוגדר!

volumes:
  mongo-data:
  caddy_data:
  caddy_config:

networks:
  myapp_network:
    driver: bridge
