name: Build and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build React and Deploy via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Client Dependencies
      working-directory: /client
      run: npm install

    - name: Build React App
      working-directory: /client
      run: npm run build

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rsync build and server files to remote
      run: |
        rsync -avz --delete \
          ./client/build/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/myapp/client/build

        rsync -avz --exclude='.git*' ./server/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/myapp/server

        rsync -avz docker-compose.yml Caddyfile ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/myapp/

    - name: Run Docker Compose on Remote
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd /home/ubuntu/myapp
          docker-compose pull
          docker-compose build
          docker-compose up -d
        EOF
